### ISSUE TITLE
Doesn't seem to be working on my second pc. Tried on my main pc and works flawlessly tho. Any suggestions?

### ISSUE THREAD

**Issue by mapadin** [Deathstroke751/AutoPresearch#1]
DevTools listening on ws://127.0.0.1:61836/devtools/browser/c9e81c6a-41b1-46f4-bb70-9d9f729a4102
[0926/215350.327:INFO:CONSOLE(0)] "Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.", source:  (0)
[0926/215350.328:INFO:CONSOLE(0)] "Error with Feature-Policy header: Unrecognized feature: 'speaker'.", source:  (0)
[0926/215350.328:INFO:CONSOLE(0)] "Error with Feature-Policy header: Unrecognized feature: 'vr'.", source:  (0)
Traceback (most recent call last):
  File "C:\Users\M\Desktop\presearch\presearch.py", line 66, in <module>
    tps = driver.find_element_by_xpath('//*[@id="main"]/div[2]/div[1]/div[1]/div/div')
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="main"]/div[2]/div[1]/div[1]/div/div"}
  (Session info: headless chrome=94.0.4606.61)

**Comment by Deathstroke751** [comment]
Check if you're logged in on Chrome. That might be it ig.
